sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: cangqiong
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  jwt:
#    admin-token-name: authorization
    admin-token-name: token
    user-secret-key: itheuma
    user-ttl: 7200000
    user-token-name: authentication
  wechat:
    appid: id
    secret: secret
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: java--------------ai
    region: cn-beijing
    access-key-id: yourid
    access-key-secret: yoursecret